// Customer-facing Supabase client.
// Runs in the browser (Expo Web) with the anon key — no auth session.
// RLS policies grant anon access only to public menu data and customer orders.

import { createClient } from '@supabase/supabase-js'
import { Config } from '../../constants/config'

// Public client — used for menu/shop reads (no session required).
export const supabaseCustomer = createClient(
  Config.supabase.url,
  Config.supabase.anonKey,
  {
    auth: {
      // Customers are anonymous — no session persistence needed
      persistSession: false,
      autoRefreshToken: false,
      detectSessionInUrl: false,
    },
  }
)

/**
 * Returns a Supabase client scoped to a specific customer session.
 * The session UUID is sent as `x-customer-session` request header so
 * the RLS helper `get_customer_session_id()` can enforce row isolation.
 *
 * Call this ONCE per page load with the session UUID generated by the
 * customer.tsx component, then use the returned client for all
 * order/order_items/payments reads.
 */
export function createSessionedCustomerClient(sessionId: string) {
  return createClient(
    Config.supabase.url,
    Config.supabase.anonKey,
    {
      auth: {
        persistSession: false,
        autoRefreshToken: false,
        detectSessionInUrl: false,
      },
      global: {
        headers: {
          'x-customer-session': sessionId,
        },
      },
    }
  )
}
