import { create } from 'zustand'
import { immer } from 'zustand/middleware/immer'
import { supabase } from '../lib/supabase'
import { Order, OrderWithItems, CartItem, Payment } from '../types'
import { generatePromptPayPayload, generateQRReference } from '../lib/qr'
import { Config } from '../../constants/config'

interface OrderState {
  orders: OrderWithItems[]
  currentOrder: OrderWithItems | null
  isLoading: boolean
  fetchError: string | null

  createOrder: (
    shopId: string,
    cashierId: string,
    items: CartItem[],
    paymentMethod: 'cash' | 'qr' | 'card',
    discount: number,
    taxRate: number
  ) => Promise<Order>
  updateOrderStatus: (orderId: string, status: string) => Promise<void>
  completeOrder: (orderId: string, paymentData: Partial<Payment>, confirmationType: 'manual' | 'auto', confirmedBy?: string) => Promise<void>
  cancelOrder: (orderId: string, cancelledBy: string, reason?: string) => Promise<void>
  fetchOrders: (shopId: string, limit?: number) => Promise<void>
  subscribeToOrder: (orderId: string) => () => void
}

export const useOrderStore = create<OrderState>()(
  immer((set, get) => ({
    orders: [],
    currentOrder: null,
    isLoading: false,
    fetchError: null,

    createOrder: async (
      shopId: string,
      cashierId: string,
      items: CartItem[],
      paymentMethod: 'cash' | 'qr' | 'card',
      discount: number = 0,
      taxRate: number = Config.tax.rate
    ): Promise<Order> => {
      set((state) => {
        state.isLoading = true
      })

      try {
        const subtotal = items.reduce((sum, item) => sum + item.subtotal, 0)
        const discountAmount = subtotal * (discount / 100)
        // Tax is inclusive (VAT already in price): extract tax from the after-discount amount
        const afterDiscount = subtotal - discountAmount
        const taxAmount = afterDiscount * (taxRate / (1 + taxRate))
        const totalAmount = afterDiscount

        // 1. Insert order (order_number auto-generated by DB sequence)
        const { data: order, error: orderError } = await supabase
          .from('orders')
          .insert({
            shop_id: shopId,
            cashier_id: cashierId,
            subtotal,
            discount_amount: discountAmount,
            tax_amount: taxAmount,
            total_amount: totalAmount,
            payment_method: paymentMethod,
            status: 'pending',
          })
          .select()
          .single()

        if (orderError) throw orderError

        // 2. Insert order items (no product_name column)
        const orderItems = items.map((item) => ({
          order_id: order.id,
          product_id: item.product.id,
          quantity: item.quantity,
          unit_price: item.product.price,
          subtotal: item.subtotal,
        }))

        const { error: itemsError } = await supabase
          .from('order_items')
          .insert(orderItems)

        if (itemsError) throw itemsError

        // 3. Insert pending payment
        // H-4: Fetch promptpay_id from shops table rather than bundled EXPO_PUBLIC env var
        let qrPayload: string | undefined = undefined
        if (paymentMethod === 'qr') {
          const { data: shopRow } = await supabase
            .from('shops')
            .select('promptpay_id')
            .eq('id', shopId)
            .single()
          const promptPayId = shopRow?.promptpay_id ?? ''
          if (promptPayId) {
            qrPayload = generatePromptPayPayload(promptPayId, totalAmount)
          }
        }

        const { data: payment, error: paymentError } = await supabase
          .from('payments')
          .insert({
            order_id: order.id,
            method: paymentMethod,
            amount: totalAmount,
            qr_payload: qrPayload,
            transaction_ref: generateQRReference(),
            status: 'pending',
          })
          .select()
          .single()

        if (paymentError) throw paymentError

        const fullOrder: OrderWithItems = {
          ...order,
          items: orderItems.map((item, i) => ({ ...item, id: `temp-${i}` })),
          payment,
        }

        set((state) => {
          state.currentOrder = fullOrder as any
          state.isLoading = false
        })

        return order as Order
      } catch (err: any) {
        set((state) => {
          state.isLoading = false
        })
        throw err
      }
    },

    updateOrderStatus: async (orderId: string, status: string) => {
      const updateData: any = { status }
      if (status === 'completed') {
        updateData.completed_at = new Date().toISOString()
      }
      const { error } = await supabase
        .from('orders')
        .update(updateData)
        .eq('id', orderId)

      if (error) throw error

      set((state) => {
        const order = state.orders.find((o) => o.id === orderId)
        if (order) order.status = status as any
        if (state.currentOrder?.id === orderId) {
          state.currentOrder.status = status as any
        }
      })
    },

    completeOrder: async (orderId: string, paymentData: Partial<Payment>, confirmationType: 'manual' | 'auto', confirmedBy?: string) => {
      const { error: paymentError } = await supabase
        .from('payments')
        .update({
          ...paymentData,
          status: 'success',
          confirmation_type: confirmationType,
          confirmed_by: confirmedBy ?? null,
          updated_at: new Date().toISOString(),
        })
        .eq('order_id', orderId)

      if (paymentError) throw paymentError

      const { error: orderError } = await supabase
        .from('orders')
        .update({
          status: 'completed',
          completed_at: new Date().toISOString(),
        })
        .eq('id', orderId)

      if (orderError) throw orderError

      set((state) => {
        const order = state.orders.find((o) => o.id === orderId)
        if (order) order.status = 'completed'
        if (state.currentOrder?.id === orderId) {
          state.currentOrder.status = 'completed'
        }
      })
    },

    cancelOrder: async (orderId: string, cancelledBy: string, reason?: string) => {
      const now = new Date().toISOString()

      const { error: orderError } = await supabase
        .from('orders')
        .update({
          status: 'cancelled',
          cancelled_at: now,
          cancelled_by: cancelledBy,
          cancel_reason: reason ?? null,
        })
        .eq('id', orderId)

      if (orderError) throw orderError

      // Mark payment as failed if it exists and is still pending
      await supabase
        .from('payments')
        .update({ status: 'failed' })
        .eq('order_id', orderId)
        .eq('status', 'pending')

      set((state) => {
        const order = state.orders.find((o) => o.id === orderId)
        if (order) {
          order.status = 'cancelled'
          order.cancelled_at = now
          order.cancelled_by = cancelledBy
          order.cancel_reason = reason ?? null
        }
        if (state.currentOrder?.id === orderId) {
          state.currentOrder.status = 'cancelled'
        }
      })
    },

    fetchOrders: async (shopId: string, limit: number = 50) => {
      set((state) => {
        state.isLoading = true
        state.fetchError = null
      })

      try {
        const { data, error } = await supabase
          .from('orders')
          .select('*, items:order_items(*), payment:payments(*, confirmed_by_profile:profiles!payments_confirmed_by_fkey(full_name)), cancelled_by_profile:profiles!orders_cancelled_by_fkey(full_name)')
          .eq('shop_id', shopId)
          .order('created_at', { ascending: false })
          .limit(limit)

        if (error) throw error

        set((state) => {
          state.orders = (data || []).map((o: any) => {
            // Supabase returns payment as object (not array) because payments.order_id is UNIQUE
            const rawPayment = Array.isArray(o.payment) ? o.payment[0] : o.payment
            const confirmedByProfile = rawPayment?.confirmed_by_profile ?? undefined
            const payment = rawPayment
              ? { ...rawPayment, confirmed_by_profile: undefined }
              : undefined
            const cancelledByProfile = o.cancelled_by_profile ?? undefined
            return {
              ...o,
              payment,
              confirmedByProfile,
              cancelledByProfile,
              cancelled_by_profile: undefined,
            }
          }) as OrderWithItems[]
          state.isLoading = false
        })
      } catch (err: any) {
        set((state) => {
          state.isLoading = false
          state.fetchError = err?.message ?? 'โหลดรายการออเดอร์ไม่ได้ กรุณาตรวจสอบสัญญาณอินเทอร์เน็ต'
        })
      }
    },

    subscribeToOrder: (orderId: string) => {
      const channel = supabase
        .channel(`order-payment:${orderId}`)
        .on(
          'postgres_changes',
          {
            event: 'UPDATE',
            schema: 'public',
            table: 'payments',
            filter: `order_id=eq.${orderId}`,
          },
          (payload) => {
            const newPayment = payload.new as Payment
            set((state) => {
              if (state.currentOrder?.id === orderId) {
                state.currentOrder.payment = newPayment
                if (newPayment.status === 'success') {
                  state.currentOrder.status = 'completed'
                }
              }
            })
            // Auto-confirm: when payment arrives as success from external source
            if (newPayment.status === 'success' && !newPayment.confirmation_type) {
              get().completeOrder(orderId, newPayment, 'auto')
            }
          }
        )
        .subscribe()

      return () => {
        channel.unsubscribe()
      }
    },
  }))
)
